# Generated by Django 3.0.4 on 2020-03-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=256)),
                ('botanical_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('germination_days', models.IntegerField()),
                ('pot_on_days', models.IntegerField()),
                ('transplant_days', models.IntegerField()),
                ('first_harvest_days', models.IntegerField()),
                ('harvest_type', models.IntegerField(choices=[('1', 'Single Harvest'), ('2', 'Continuous Harvest'), ('3', 'Multiple Harvest')], default='1')),
                ('preferred_sun', models.IntegerField(choices=[('1', 'Full Sun'), ('2', 'Sun/Shade'), ('3', 'Shade')], default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('sow_date', models.DateField()),
                ('germinate_date', models.DateField()),
                ('pot_on_date', models.DateField()),
                ('transplant_date', models.DateField()),
                ('first_harvest_date', models.DateField()),
                ('last_harvest_date', models.DateField()),
                ('harvested', models.BooleanField(default=False)),
                ('total_yield', models.IntegerField(help_text='Yield in KG')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GardenTracker.Seed')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='notes/')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GardenTracker.Plant')),
                ('seed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GardenTracker.Seed')),
            ],
        ),
    ]
