# Generated by Django 3.0.4 on 2020-03-16 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GardenTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notes/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='plant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GardenTracker.Plant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='seed_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GardenTracker.Seed'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='first_harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='germinate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='harvested',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='last_harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pot_on_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='total_yield',
            field=models.IntegerField(blank=True, help_text='Yield in KG', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='transplant_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='botanical_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='first_harvest_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='germination_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='pot_on_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='transplant_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='preferred_soil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='GardenTracker.Soil'),
        ),
    ]
