# Generated by Django 3.0.4 on 2020-03-16 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenTracker', '0002_auto_20200316_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sow_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='seed',
            name='botanical_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='seed',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='soil',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
